### ISSUE TITLE
MATLAB

### ISSUE THREAD

**Issue by qlahcim** [juanjonrg/nds#1]
Hi, will be possible to add any suitable way to directly call your seq_nds, mult_nds and cude_nds functions from MATLAB (via MEX files, or CUDA kernel)?

I am not experienced C or CUDA programmer, but I am really very interested to test and use your parallelized nds function in my multi-objective combinatorial optimization project.

**Comment by juanjonrg** [comment]
Hi, thank you for your interest in this project.

I think it is possible to make MEX entrypoints for these functions, please give me a couple of days so I can get a working prototype.

**Comment by juanjonrg** [comment]
Hi again,

I've added MEX entrypoints to all implementations and a [small MATLAB script](https://github.com/juanjonrg/nds/blob/850af339613fe2c4ecf0fc5e1b2c44478f50fab1/src/mex/mex_nds.m) with examples on how to compile and use them.

I've tested them on MATLAB R2018a. The compilation of the MEX CUDA version requires the Parallel Computing Toolbox and (in my case) CUDA SDK 9.0. Please keep in mind that the performance may vary from the original C code due to the overhead introduced by MATLAB.

Good luck!

**Comment by qlahcim** [comment]
Thanks a lot!!! I will test the mex files asap …
